name: dfm
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - numpy
  - pandas
  - click
  - pytorch
  - cudatoolkit=11.3
  - pytest
  - jupyterlab
  - bunch
  - matplotlib
  - seaborn
  - scikit-learn
  - pip
  - pip:
